import os

from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv('BOT_TOKEN')
PAYMENTS_API_TOKEN = os.getenv('PAYMENTS_API_TOKEN')
CHANNEL_ID = os.getenv('CHANNEL_ID')
DATABASE_URL = os.getenv('DATABASE_URL')
CHAT_OWNER_ID = int(os.getenv('CHAT_OWNER_ID'))
CSV_FILE_PATH = os.getenv('CSV_FILE_PATH')

MONTH_SUBSCRIPTION_PRICE = os.getenv('MONTH_SUBSCRIPTION_PRICE')
MONTH_SUBSCRIPTION_PRICE_WITH_DISCOUNT = os.getenv('MONTH_SUBSCRIPTION_PRICE_WITH_DISCOUNT')

THREE_MONTHS_SUBSCRIPTION_PRICE = os.getenv('THREE_MONTHS_SUBSCRIPTION_PRICE')
THREE_MONTHS_SUBSCRIPTION_PRICE_WITH_DISCOUNT = os.getenv('THREE_MONTHS_SUBSCRIPTION_PRICE_WITH_DISCOUNT')
